# Generated by Django 5.0.6 on 2024-06-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedFileLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(max_length=100)),
                ('file_name', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
